### ISSUE TITLE
could not run Tutorial_1 on GPU:@mpc.run_multiprocess(world_size=2)

### ISSUE THREAD

**Issue by maminiris** [facebookresearch/CrypTen#481]
Dear expert:

   I try to run tutorial_1 on GPU:
 #!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2023/7/3 20:56
# @Author  : archer_oneee
# @File    : mm.py
# @Software: PyCharm

import crypten
import time

import crypten.mpc as mpc
import torch
# Create torch tensor
import multiprocessing as mp

crypten.init()
torch.set_num_threads(1)

x_enc = crypten.cryptensor([[1.0, 2.0, 3.0,8.7],[4.0,5.0,6.0,8.7]])

y_enc = crypten.cryptensor([1.0, 2.0,3.0,6.6])

@mpc.run_multiprocess(world_size=2)
def examine_arithmetic_shares():

    x_enc = crypten.cryptensor([[2,3], [3,5]],ptype=crypten.mpc.arithmetic)
    y_enc = crypten.cryptensor([[0.004,0.003], [0.002,0.003]],ptype=crypten.mpc.arithmetic)
    t1 = time.time()
    z_enc = x_enc.sqrt()
    t2 = time.time()
    print('t',t2-t1)
    print("Private inv_sqrt", z_enc.get_plain_text())
    return t2-t1

mp.set_start_method('fork')
x = examine_arithmetic_shares()

-------------------------------------------------------------------------------

But failed for CUDA init :
Process Process-1:
Process Process-2:
Traceback (most recent call last):
  File "/data/home/scv8545/.conda/envs/torch/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/data/home/scv8545/.conda/envs/torch/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/scv8545/.conda/envs/torch/lib/python3.7/site-packages/crypten/mpc/context.py", line 29, in _launch
    crypten.init()
  File "/data/home/scv8545/.conda/envs/torch/lib/python3.7/site-packages/crypten/__init__.py", line 77, in init
    _setup_prng()
  File "/data/home/scv8545/.conda/envs/torch/lib/python3.7/site-packages/crypten/__init__.py", line 202, in _setup_prng
    generators[key][device] = torch.Generator(device=device)
RuntimeError: CUDA error: initialization error
Traceback (most recent call last):
  File "/data/home/scv8545/.conda/envs/torch/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/data/home/scv8545/.conda/envs/torch/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/scv8545/.conda/envs/torch/lib/python3.7/site-packages/crypten/mpc/context.py", line 29, in _launch
    crypten.init()
  File "/data/home/scv8545/.conda/envs/torch/lib/python3.7/site-packages/crypten/__init__.py", line 77, in init
    _setup_prng()
  File "/data/home/scv8545/.conda/envs/torch/lib/python3.7/site-packages/crypten/__init__.py", line 202, in _setup_prng
    generators[key][device] = torch.Generator(device=device)
RuntimeError: CUDA error: initialization error
ERROR:root:One of the parties failed. Check past logs

**Comment by tanjuntao** [comment]
Could you please tell me how you solve this problem? Thanks.

**Comment by maminiris** [comment]
sorry,I solved it several months ago,I already forget it.but their code is right



---Original---
From: "Juntao ***@***.***&gt;
Date: Thu, Dec 28, 2023 19:31 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [facebookresearch/CrypTen] could not run Tutorial_1 ***@***.***_multiprocess(world_size=2) (Issue #481)




 
Could you please tell me how you solve this problem? Thanks.

**Comment by maminiris** [comment]
请问你是怎么通过github给我发邮件的？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/CrypTen"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月28日(星期四) 晚上7:31
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/CrypTen] could not run Tutorial_1 on ***@***.***_multiprocess(world_size=2) (Issue #481)





 
Could you please tell me how you solve this problem? Thanks.

**Comment by manel1874** [comment]
I also have the same issue. It should be related with CUDA not being installed properly. An easy way to make it run without looking into the gpu drivers is to disable it in the python/jupyter file. You can do that with these two lines in the beginning of the notebook:

```python
import os
os.environ["CUDA_VISIBLE_DEVICES"]=""
```

You can check more ways to do it [here](https://stackoverflow.com/questions/53266350/how-to-tell-pytorch-to-not-use-the-gpu).
